import { createStudioLayer, createStudioPatch, type StudioPatch } from './types'

export const STUDIO_PATCHES: StudioPatch[] = [
  createStudioPatch({
    id: 'stacked-click',
    name: 'Stacked Click',
    description: 'Two layers: a bright impact body and a short air layer for expensive-feeling taps.',
    durationMs: 360,
    master: {
      gain: 0.88,
      drive: 0.18,
      delayMix: 0.05,
      delayMs: 90,
      delayFeedback: 0.18,
      stereoWidth: 0.92,
    },
    layers: [
      createStudioLayer('body', 'Impact body', {
        waveform: 'triangle',
        gain: 0.58,
        startFreq: 1640,
        endFreq: 420,
        durationMs: 170,
        transient: 0.62,
        envelope: { attackMs: 0, holdMs: 0, decayMs: 110, sustain: 0.12, releaseMs: 60 },
        filter: { type: 'lowpass', cutoffHz: 7600, resonance: 1.2, envelopeAmount: 0.9 },
      }),
      createStudioLayer('air', 'Air snap', {
        waveform: 'sawtooth',
        gain: 0.22,
        pan: 0.18,
        noise: 0.52,
        startFreq: 3200,
        endFreq: 880,
        startMs: 8,
        durationMs: 110,
        transient: 0.3,
        envelope: { attackMs: 0, holdMs: 0, decayMs: 85, sustain: 0, releaseMs: 25 },
        filter: { type: 'bandpass', cutoffHz: 2800, resonance: 1.6, envelopeAmount: 0.4 },
      }),
    ],
  }),
  createStudioPatch({
    id: 'glass-reward',
    name: 'Glass Reward',
    description: 'Bell-like reward tone with a stereo shimmer layer and a faint delayed tail.',
    durationMs: 760,
    master: {
      gain: 0.78,
      drive: 0.08,
      delayMix: 0.18,
      delayMs: 180,
      delayFeedback: 0.34,
      stereoWidth: 1.25,
    },
    layers: [
      createStudioLayer('core', 'Glass core', {
        waveform: 'sine',
        gain: 0.46,
        pan: -0.12,
        noise: 0.06,
        startFreq: 680,
        endFreq: 1320,
        durationMs: 340,
        vibratoDepth: 12,
        vibratoRate: 7.4,
        transient: 0.16,
        envelope: { attackMs: 6, holdMs: 16, decayMs: 220, sustain: 0.32, releaseMs: 180 },
        filter: { type: 'lowpass', cutoffHz: 9800, resonance: 0.9, envelopeAmount: 0.4 },
      }),
      createStudioLayer('spark', 'Sparkle layer', {
        waveform: 'square',
        gain: 0.2,
        pan: 0.32,
        noise: 0.08,
        startFreq: 1800,
        endFreq: 2600,
        startMs: 28,
        durationMs: 220,
        vibratoDepth: 8,
        vibratoRate: 12.6,
        transient: 0.22,
        envelope: { attackMs: 0, holdMs: 0, decayMs: 130, sustain: 0.08, releaseMs: 120 },
        filter: { type: 'highpass', cutoffHz: 2200, resonance: 1.1, envelopeAmount: 0.2 },
      }),
    ],
  }),
  createStudioPatch({
    id: 'ui-whoosh',
    name: 'UI Whoosh Stack',
    description: 'A motion preset with a noisy sweep, midrange body, and a soft low-end bed.',
    durationMs: 960,
    master: {
      gain: 0.86,
      drive: 0.12,
      delayMix: 0.12,
      delayMs: 140,
      delayFeedback: 0.26,
      stereoWidth: 1.18,
    },
    layers: [
      createStudioLayer('air-sweep', 'Air sweep', {
        waveform: 'triangle',
        gain: 0.34,
        pan: 0.2,
        noise: 0.74,
        startFreq: 2100,
        endFreq: 190,
        durationMs: 620,
        transient: 0.1,
        envelope: { attackMs: 0, holdMs: 0, decayMs: 320, sustain: 0.2, releaseMs: 180 },
        filter: { type: 'bandpass', cutoffHz: 1800, resonance: 0.8, envelopeAmount: -0.2 },
      }),
      createStudioLayer('body-sweep', 'Mid body', {
        waveform: 'sawtooth',
        gain: 0.24,
        pan: -0.16,
        noise: 0.26,
        startFreq: 760,
        endFreq: 160,
        startMs: 40,
        durationMs: 540,
        transient: 0.18,
        envelope: { attackMs: 0, holdMs: 0, decayMs: 240, sustain: 0.12, releaseMs: 120 },
        filter: { type: 'lowpass', cutoffHz: 3200, resonance: 1.3, envelopeAmount: 0.5 },
      }),
      createStudioLayer('bed', 'Low bed', {
        waveform: 'sine',
        gain: 0.14,
        pan: 0,
        noise: 0.02,
        startFreq: 160,
        endFreq: 92,
        startMs: 24,
        durationMs: 700,
        transient: 0,
        envelope: { attackMs: 24, holdMs: 60, decayMs: 260, sustain: 0.42, releaseMs: 220 },
        filter: { type: 'lowpass', cutoffHz: 1100, resonance: 0.7, envelopeAmount: 0 },
      }),
    ],
  }),
]
