import { clampSoundParams, clampValue, SOUND_LIMITS, type SoundParams, type SoundPreset } from './types'

const basePresets: SoundPreset[] = [
  {
    id: 'click',
    name: 'Click Snap',
    category: 'buttons',
    tag: 'tap',
    description: 'Short and bright for buttons, tabs, and compact toggles.',
    params: {
      durationMs: 65,
      startFreq: 1850,
      endFreq: 940,
      volume: 0.66,
      noise: 0.16,
      attackMs: 0,
      decayMs: 75,
      vibratoDepth: 0,
      vibratoRate: 0,
      lowPassHz: 9600,
      transient: 0.68,
      waveform: 'triangle',
    },
  },
  {
    id: 'hover',
    name: 'Hover Blip',
    category: 'buttons',
    tag: 'hover',
    description: 'A soft lift for hover states and lightweight focus cues.',
    params: {
      durationMs: 90,
      startFreq: 720,
      endFreq: 980,
      volume: 0.4,
      noise: 0.04,
      attackMs: 2,
      decayMs: 100,
      vibratoDepth: 5,
      vibratoRate: 8.2,
      lowPassHz: 12000,
      transient: 0.22,
      waveform: 'sine',
    },
  },
  {
    id: 'toggle',
    name: 'Toggle Tick',
    category: 'buttons',
    tag: 'switch',
    description: 'Tight and mechanical for switches, segmented controls, and chips.',
    params: {
      durationMs: 58,
      startFreq: 1020,
      endFreq: 710,
      volume: 0.5,
      noise: 0.12,
      attackMs: 0,
      decayMs: 90,
      vibratoDepth: 0,
      vibratoRate: 0,
      lowPassHz: 8200,
      transient: 0.74,
      waveform: 'sawtooth',
    },
  },
  {
    id: 'double-click',
    name: 'Double Click',
    category: 'buttons',
    tag: 'double',
    description: 'A twin-tap accent for double actions, open states, and card launch cues.',
    params: {
      durationMs: 120,
      startFreq: 1420,
      endFreq: 760,
      volume: 0.54,
      noise: 0.13,
      attackMs: 0,
      decayMs: 95,
      vibratoDepth: 0,
      vibratoRate: 0,
      lowPassHz: 8700,
      transient: 0.72,
      waveform: 'sawtooth',
    },
  },
  {
    id: 'toggle-on',
    name: 'Toggle On',
    category: 'buttons',
    tag: 'on',
    description: 'A short upward tick for enabling switches and activating compact controls.',
    params: {
      durationMs: 72,
      startFreq: 620,
      endFreq: 1380,
      volume: 0.48,
      noise: 0.05,
      attackMs: 0,
      decayMs: 90,
      vibratoDepth: 4,
      vibratoRate: 7.8,
      lowPassHz: 11000,
      transient: 0.58,
      waveform: 'triangle',
    },
  },
  {
    id: 'toggle-off',
    name: 'Toggle Off',
    category: 'buttons',
    tag: 'off',
    description: 'A descending answer for disabling switches or collapsing lightweight UI.',
    params: {
      durationMs: 78,
      startFreq: 1280,
      endFreq: 520,
      volume: 0.46,
      noise: 0.08,
      attackMs: 0,
      decayMs: 95,
      vibratoDepth: 0,
      vibratoRate: 0,
      lowPassHz: 7600,
      transient: 0.56,
      waveform: 'triangle',
    },
  },
  {
    id: 'pop',
    name: 'Pop Bubble',
    category: 'feedback',
    tag: 'pop',
    description: 'Rounded and playful for confirmations or small reactions.',
    params: {
      durationMs: 135,
      startFreq: 520,
      endFreq: 170,
      volume: 0.6,
      noise: 0.14,
      attackMs: 0,
      decayMs: 160,
      vibratoDepth: 0,
      vibratoRate: 0,
      lowPassHz: 7200,
      transient: 0.54,
      waveform: 'sine',
    },
  },
  {
    id: 'success',
    name: 'Success Chime',
    category: 'feedback',
    tag: 'good',
    description: 'An upbeat rise that works for saved states and confirmations.',
    params: {
      durationMs: 280,
      startFreq: 480,
      endFreq: 1260,
      volume: 0.52,
      noise: 0.03,
      attackMs: 4,
      decayMs: 270,
      vibratoDepth: 10,
      vibratoRate: 6.1,
      lowPassHz: 9400,
      transient: 0.16,
      waveform: 'triangle',
    },
  },
  {
    id: 'confirm',
    name: 'Confirm Bloom',
    category: 'feedback',
    tag: 'save',
    description: 'Warm and compact for saved forms, completed steps, and gentle approvals.',
    params: {
      durationMs: 210,
      startFreq: 430,
      endFreq: 980,
      volume: 0.48,
      noise: 0.06,
      attackMs: 3,
      decayMs: 220,
      vibratoDepth: 8,
      vibratoRate: 5.6,
      lowPassHz: 8800,
      transient: 0.2,
      waveform: 'sine',
    },
  },
  {
    id: 'error',
    name: 'Error Buzz',
    category: 'alerts',
    tag: 'warn',
    description: 'A descending buzz for validation failures or blocked actions.',
    params: {
      durationMs: 300,
      startFreq: 340,
      endFreq: 140,
      volume: 0.56,
      noise: 0.18,
      attackMs: 0,
      decayMs: 260,
      vibratoDepth: 11,
      vibratoRate: 10.4,
      lowPassHz: 3600,
      transient: 0.3,
      waveform: 'square',
    },
  },
  {
    id: 'notification',
    name: 'Notification Ping',
    category: 'alerts',
    tag: 'ping',
    description: 'A clean attention cue for inbox updates, mentions, and reminders.',
    params: {
      durationMs: 240,
      startFreq: 880,
      endFreq: 1220,
      volume: 0.44,
      noise: 0.04,
      attackMs: 2,
      decayMs: 190,
      vibratoDepth: 6,
      vibratoRate: 7.4,
      lowPassHz: 10800,
      transient: 0.3,
      waveform: 'triangle',
    },
  },
  {
    id: 'caution',
    name: 'Caution Pulse',
    category: 'alerts',
    tag: 'alert',
    description: 'A softer warning pulse for inline notices and recoverable problems.',
    params: {
      durationMs: 260,
      startFreq: 640,
      endFreq: 420,
      volume: 0.5,
      noise: 0.12,
      attackMs: 0,
      decayMs: 220,
      vibratoDepth: 8,
      vibratoRate: 9.4,
      lowPassHz: 5200,
      transient: 0.34,
      waveform: 'square',
    },
  },
  {
    id: 'whoosh',
    name: 'Micro Whoosh',
    category: 'motion',
    tag: 'motion',
    description: 'A compact motion accent for panels, drawers, and subtle reveals.',
    params: {
      durationMs: 430,
      startFreq: 1400,
      endFreq: 220,
      volume: 0.46,
      noise: 0.62,
      attackMs: 0,
      decayMs: 360,
      vibratoDepth: 0,
      vibratoRate: 0,
      lowPassHz: 2600,
      transient: 0.14,
      waveform: 'triangle',
    },
  },
  {
    id: 'menu-swish',
    name: 'Menu Swish',
    category: 'motion',
    tag: 'menu',
    description: 'A quick airy sweep for menus, dropdowns, and command palette reveals.',
    params: {
      durationMs: 210,
      startFreq: 1900,
      endFreq: 340,
      volume: 0.42,
      noise: 0.45,
      attackMs: 0,
      decayMs: 200,
      vibratoDepth: 0,
      vibratoRate: 0,
      lowPassHz: 4200,
      transient: 0.2,
      waveform: 'sawtooth',
    },
  },
  {
    id: 'drawer-lift',
    name: 'Drawer Lift',
    category: 'motion',
    tag: 'lift',
    description: 'A light rising motion cue for sheets, drawers, and floating panels.',
    params: {
      durationMs: 260,
      startFreq: 260,
      endFreq: 900,
      volume: 0.4,
      noise: 0.28,
      attackMs: 0,
      decayMs: 220,
      vibratoDepth: 0,
      vibratoRate: 0,
      lowPassHz: 5600,
      transient: 0.24,
      waveform: 'triangle',
    },
  },
  {
    id: 'sparkle',
    name: 'Sparkle Tick',
    category: 'rewards',
    tag: 'spark',
    description: 'A crisp high-end accent for rewards, badges, and unlocks.',
    params: {
      durationMs: 175,
      startFreq: 1450,
      endFreq: 2280,
      volume: 0.4,
      noise: 0.08,
      attackMs: 0,
      decayMs: 150,
      vibratoDepth: 14,
      vibratoRate: 12.6,
      lowPassHz: 12000,
      transient: 0.48,
      waveform: 'square',
    },
  },
  {
    id: 'coin',
    name: 'Coin Blink',
    category: 'rewards',
    tag: 'coin',
    description: 'An arcade-like prize accent for points, pickups, and streak rewards.',
    params: {
      durationMs: 180,
      startFreq: 900,
      endFreq: 1800,
      volume: 0.44,
      noise: 0.03,
      attackMs: 0,
      decayMs: 160,
      vibratoDepth: 13,
      vibratoRate: 10,
      lowPassHz: 11800,
      transient: 0.44,
      waveform: 'square',
    },
  },
  {
    id: 'unlock',
    name: 'Unlock Glint',
    category: 'rewards',
    tag: 'unlock',
    description: 'A polished rise for achievements, feature unlocks, and fresh access granted.',
    params: {
      durationMs: 240,
      startFreq: 520,
      endFreq: 1640,
      volume: 0.46,
      noise: 0.04,
      attackMs: 2,
      decayMs: 220,
      vibratoDepth: 9,
      vibratoRate: 7,
      lowPassHz: 10400,
      transient: 0.26,
      waveform: 'triangle',
    },
  },
  {
    id: 'badge',
    name: 'Badge Shine',
    category: 'rewards',
    tag: 'badge',
    description: 'A tiny celebratory glimmer for level-ups, milestones, and earned labels.',
    params: {
      durationMs: 150,
      startFreq: 1100,
      endFreq: 1480,
      volume: 0.36,
      noise: 0.05,
      attackMs: 0,
      decayMs: 110,
      vibratoDepth: 10,
      vibratoRate: 12,
      lowPassHz: 12000,
      transient: 0.38,
      waveform: 'sine',
    },
  },
]

export const PRESETS: SoundPreset[] = basePresets.map((preset) => ({
  ...preset,
  params: clampSoundParams(preset.params),
}))

export function varySoundParams(source: SoundParams, random: () => number = Math.random): SoundParams {
  const drift = () => random() * 2 - 1
  const scale = (value: number, amount: number, min: number, max: number) =>
    clampValue(value * (1 + drift() * amount), min, max)
  const shift = (value: number, amount: number, min: number, max: number) =>
    clampValue(value + drift() * amount, min, max)

  return clampSoundParams({
    ...source,
    durationMs: scale(source.durationMs, 0.22, SOUND_LIMITS.durationMs.min, SOUND_LIMITS.durationMs.max),
    startFreq: scale(source.startFreq, 0.18, SOUND_LIMITS.startFreq.min, SOUND_LIMITS.startFreq.max),
    endFreq: scale(source.endFreq, 0.18, SOUND_LIMITS.endFreq.min, SOUND_LIMITS.endFreq.max),
    volume: shift(source.volume, 0.08, SOUND_LIMITS.volume.min, SOUND_LIMITS.volume.max),
    noise: shift(source.noise, 0.12, SOUND_LIMITS.noise.min, SOUND_LIMITS.noise.max),
    attackMs: shift(source.attackMs, 12, SOUND_LIMITS.attackMs.min, SOUND_LIMITS.attackMs.max),
    decayMs: scale(source.decayMs, 0.25, SOUND_LIMITS.decayMs.min, SOUND_LIMITS.decayMs.max),
    vibratoDepth: shift(
      source.vibratoDepth,
      10,
      SOUND_LIMITS.vibratoDepth.min,
      SOUND_LIMITS.vibratoDepth.max,
    ),
    vibratoRate: shift(source.vibratoRate, 2.4, SOUND_LIMITS.vibratoRate.min, SOUND_LIMITS.vibratoRate.max),
    lowPassHz: scale(source.lowPassHz, 0.22, SOUND_LIMITS.lowPassHz.min, SOUND_LIMITS.lowPassHz.max),
    transient: shift(source.transient, 0.16, SOUND_LIMITS.transient.min, SOUND_LIMITS.transient.max),
  })
}
